version: "0.1"

subdomains:
  flask-subdomain:
    module: nullstone/aws-autogen-subdomain

apps:
  aspnet:
    module: nullstone/aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 9000
    capabilities:
      - module: nullstone/aws-load-balancer
        connections:
          subdomain: flask-subdomain
